name: littlelives-appointment-app

services:
  redis:
    container_name: littlelives_redis
    image: redis:6.2-alpine
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASS} --port ${REDIS_PORT}
    volumes:
      - redis_data:/data

  mongo:
    container_name: littlelives_mongo
    image: mongo:jammy
    restart: always
    command: --port ${MONGO_PORT}
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongodb_data:/data:db
      - ./backend/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

  app:
    container_name: littlelives_app
    build:
      dockerfile: Dockerfile
      target: development
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .github/
            - .next/
            - .vscode
            - dist/
            - node_modules/
        - action: rebuild
          path: package.json
        - action: sync+restart
          path: .env
          target: /app/.env
    depends_on:
      - mongo
      - redis
    ports:
      - ${WEBAPP_PORT}:${WEBAPP_PORT}
    restart: always

volumes:
  mongodb_data:
  redis_data:
